"""Service-request store, SQLite. Source: design doc lines 130, 265, 357."""

import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "service_requests.db"

# seq is generated by SQLite inside the INSERT, so two concurrent writers can
# never compute the same id. The partial unique index makes "at most one open
# request of a type per order" a database guarantee, not a check-then-insert
# race. order_id is nullable: a technical-failure handoff can happen before
# any order was identified (A6: every escalate leaves a record).
_SCHEMA = """
CREATE TABLE IF NOT EXISTS service_requests (
    seq INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL,
    customer_id TEXT NOT NULL,
    order_id TEXT,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    summary TEXT NOT NULL,
    source_ids TEXT NOT NULL,
    run_id TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_open_request
    ON service_requests(order_id, type) WHERE status = 'open';
"""


def format_id(seq: int) -> str:
    return f"SR-{seq:06d}"


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH, timeout=5.0)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    columns = [row[1] for row in conn.execute("PRAGMA table_info(service_requests)")]
    if columns and "seq" not in columns:
        # Pre-v2 file (text id computed as COUNT(*)+1). Keep its rows, out of the way.
        try:
            conn.execute("ALTER TABLE service_requests RENAME TO service_requests_legacy_v1")
        except sqlite3.OperationalError:
            pass  # another process migrated it first
    conn.executescript(_SCHEMA)
    return conn


def create_request(
    customer_id: str,
    order_id: str | None,
    type_: str,
    source_ids: list[str],
    summary: str,
    run_id: str,
) -> str:
    """Creates a record, or returns the id of an existing open request of the
    same type for the same order (idempotent — design line 265: "אם כבר קיימת
    בקשה פתוחה מאותו סוג לאותה הזמנה, מוחזר המזהה הקיים"). Only real action
    performed is this DB write — no actual cancellation/refund (test line 85).
    Raises sqlite3.Error on failure; the caller must not quote an id then.
    """
    conn = _connect()
    try:
        with conn:
            cur = conn.execute(
                "INSERT OR IGNORE INTO service_requests "
                "(created_at, customer_id, order_id, type, status, summary, source_ids, run_id) "
                "VALUES (datetime('now'), ?, ?, ?, 'open', ?, ?, ?)",
                (customer_id, order_id, type_, summary, ",".join(source_ids), run_id),
            )
            if cur.rowcount == 1:
                return format_id(cur.lastrowid)
            existing = conn.execute(
                "SELECT seq FROM service_requests WHERE order_id = ? AND type = ? AND status = 'open'",
                (order_id, type_),
            ).fetchone()
            if existing is None:
                raise sqlite3.IntegrityError("insert ignored but no open request found")
            return format_id(existing[0])
    finally:
        conn.close()
